language: node_js
node_js:
  - "6.6.0"
before_script:
  - npm i
  - node_modules/gulp/bin/gulp.js build
script:
  - node_modules/gulp/bin/gulp.js test
notifications:
  irc:
    channels:
      - "chat.freenode.net#vanilla-framework"
      - "chat.freenode.net#canonical-webteam"
    on_success: change
    on_failure: always
    on_success: change

language: ruby
rvm: 2.1.1
before_script:
  - gem install jekyll
  - gem install percy-cli
script:
  - jekyll build
  - percy snapshot --widths "375,768,1280" _jekyll/_site/
